syntax = "proto3";

message AppendEntriesMsg {
    int32 prefixLen = 1;
    int32 leaderCommit = 2; // called 'commitLength' in leader's perspective.
    repeated string suffix = 3;
    int32 leaderId = 4;
    int32 term = 5;
    int32 prefixTerm = 6;

    int32 leaseDuration = 7;
}


message AppendEntriesReply {
    int32 term = 1;
    bool success = 2;
    int32 ack = 3;
    int32 senderId = 4;
}

message RequestVoteMsg {
    int32 cId = 1;
    int32 cTerm = 2;
    int32 cLogLength = 3; // length of the candidate's log
    int32 cLogTerm = 4; // term number in the candidate's last log entry
}

message RequestVoteReply {
    int32 term = 1;
    bool voteGranted = 2;

    // old leader's remaining lease
    int32 oldLeaderRemainingLease = 3;
}

// Service for a raft client 
message ServeClientArgs {
  string Request = 1;
}

message ServeClientReply {
  string data = 1;
  int32 leaderId = 2;
  bool success = 3;
}

service RaftClientService {
    rpc ServeClient(ServeClientArgs) returns (ServeClientReply) {}
}

service RaftNodeServices {
    rpc AppendEntries(AppendEntriesMsg) returns (AppendEntriesReply) {}

    rpc RequestVote(RequestVoteMsg) returns (RequestVoteReply) {}
}