# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"%\n\x08logEntry\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\x8f\x01\n\x10\x41ppendEntriesMsg\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.logEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\")\n\x08Response\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"^\n\x0eRequestVoteMsg\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\x32\x37\n\rAppendEntries\x12&\n\x04Send\x12\x11.AppendEntriesMsg\x1a\t.Response\"\x00\x32\x33\n\x0bRequestVote\x12$\n\x04Send\x12\x0f.RequestVoteMsg\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=51
  _globals['_APPENDENTRIESMSG']._serialized_start=54
  _globals['_APPENDENTRIESMSG']._serialized_end=197
  _globals['_RESPONSE']._serialized_start=199
  _globals['_RESPONSE']._serialized_end=240
  _globals['_REQUESTVOTEMSG']._serialized_start=242
  _globals['_REQUESTVOTEMSG']._serialized_end=336
  _globals['_APPENDENTRIES']._serialized_start=338
  _globals['_APPENDENTRIES']._serialized_end=393
  _globals['_REQUESTVOTE']._serialized_start=395
  _globals['_REQUESTVOTE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
