syntax = "proto3";

//-------------------------------------------------------------------------
// 1. Register Seller service
//-------------------------------------------------------------------------
message SellerRegisterRequest {
  string uid = 1; // uuid of seller
  string seller_address = 2; // ip:port of seller
  string notification_address = 3; // ip:port, separate, for getting notifications
}

service Register {
  // a request message which contains Seller information (defined above)
  rpc RegisterSeller(SellerRegisterRequest) returns (Reply) {}
}

message Reply {
  string message = 1; //either SUCCESS or FAIL. SUCCESS when seller does not already exists, and FAIL otherwise 
}

//-------------------------------------------------------------------------
// 2. Sell Item service. Allows a seller to post a new item on the market.
//-------------------------------------------------------------------------

message Item {
  int32 item_id = 1;
  oneof product_oneof {
    bool ELECTRONICS = 2;
    bool FASHION = 3;
    bool OTHERS = 4;
  }
  string product_name = 5;
  int32 quantity = 6;
  string description = 7;
  double price_per_unit = 8;
  string rating = 9;
  string seller_address = 10;
}

message NewItem {
  string seller_uid = 1; //seller's uid who is proposing a new item. seller must be already registered.
  oneof product_oneof {
    bool ELECTRONICS = 2;
    bool FASHION = 3;
    bool OTHERS = 4;
  }
  string product_name = 5;
  int32 quantity = 6;
  string description = 7;
  double price_per_unit_INR = 8; // price in INR (Indian National Rupees)
  string seller_address = 10;
}


service Sell {
  // seller sends request using this function.
  rpc SellItem(NewItem) returns (NewItemReply) {} 
  
}

message NewItemReply {
  oneof reply {
    int32 item_id = 1; //item id
    string fail = 2; // when FAIL happens
  }
}


//-------------------------------------------------------------------------
// 3. Update Item service
//-------------------------------------------------------------------------
message UpdateItem {
  string seller_uid = 1; //seller's uid.
  int32 item_id = 2; //item id which to update
  double new_price = 3;
  int32 new_quantity = 4;
  string seller_address = 5;
}

service Update {
  rpc UpdateItemRequest(UpdateItem) returns (Reply) {}
}


//-------------------------------------------------------------------------
// 4. Delete Item service
//-------------------------------------------------------------------------
message DeleteItem {
  string seller_uid = 1; //seller's uid.
  int32 item_id = 2; //item id which to delete
  string seller_address = 3;
}

service Delete {
  rpc DeleteItemRequest (DeleteItem) returns (Reply) {}
}

//-------------------------------------------------------------------------
// 5. Display seller items service
//-------------------------------------------------------------------------
message DisplayAllRequest {
  string seller_uid = 1; // seller's uid
  optional string seller_address = 2;
}

message Item2 { // another item type.
  int32 item_id = 1;
  string type = 2;
  string name = 3;
  int32 quantity = 4;
  string description = 5;
  double price = 6;
  int32 rating = 7;
  string seller_address = 8;
  string seller_uid = 9;
}

message ItemList {
    repeated Item2 items = 1;
}

service Display {
  rpc DisplaySellerItems (DisplayAllRequest) returns (ItemList) {}
}

// Services related to a buyer follow.
//-------------------------------------------------------------------------
// 6. Search item
//-------------------------------------------------------------------------
message SearchRequest {
  string item_name = 1; //optional
  string client_address = 2;
  oneof product_type_oneof {
    bool ELECTRONICS = 3;
    bool FASHION = 4;
    bool OTHERS = 5;
    bool ANY = 6; // ANY displays items of all categories
  }

}

service Search {
    rpc SearchItem (SearchRequest) returns (ItemList) {}
}

//-------------------------------------------------------------------------
// 7. Buy item
//-------------------------------------------------------------------------

message Buy {
  int32 item_id = 1;
  int32 quantity = 2;
  string buyer_address = 3; //ip:port of buyer
}

service BuyItem {
    rpc BuyItemRequest (Buy) returns (Reply) {}
}


//-------------------------------------------------------------------------
// 8. Add item to wish list
//-------------------------------------------------------------------------
message Wish {
    int32 item_id = 1;
    string buyer_address = 2;
    string notification_address = 3;
    string buyer_uid = 4;
}
service AddToWishList {
    rpc AddToWishListRequest (Wish) returns (Reply) {}
}

//-------------------------------------------------------------------------
// 9. Rate item
//-------------------------------------------------------------------------

message Rate {
    int32 item_id = 1;
    int32 rating = 2; // 1 to 5. Can rate only once
    string client_address = 3;
}
service RateItem {
    rpc RateItemRequest (Rate) returns (Reply) {}
}

//-------------------------------------------------------------------------
// 10. Notify client. The market sends this.
//-------------------------------------------------------------------------

service Notify {
  rpc NotifyUpdate (Item2) returns (Reply) {}
}
