# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_pb2 as market__pb2


class RegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/Register/RegisterSeller',
                request_serializer=market__pb2.SellerRegisterRequest.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class RegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterSeller(self, request, context):
        """a request message which contains Seller information (defined above)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=market__pb2.SellerRegisterRequest.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Register', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Register(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Register/RegisterSeller',
            market__pb2.SellerRegisterRequest.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SellStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SellItem = channel.unary_unary(
                '/Sell/SellItem',
                request_serializer=market__pb2.NewItem.SerializeToString,
                response_deserializer=market__pb2.NewItemReply.FromString,
                )


class SellServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SellItem(self, request, context):
        """seller sends request using this function.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=market__pb2.NewItem.FromString,
                    response_serializer=market__pb2.NewItemReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sell', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sell(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sell/SellItem',
            market__pb2.NewItem.SerializeToString,
            market__pb2.NewItemReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class UpdateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateItemRequest = channel.unary_unary(
                '/Update/UpdateItemRequest',
                request_serializer=market__pb2.UpdateItem.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class UpdateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateItemRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateItemRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemRequest,
                    request_deserializer=market__pb2.UpdateItem.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Update', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Update(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateItemRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Update/UpdateItemRequest',
            market__pb2.UpdateItem.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DeleteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteItemRequest = channel.unary_unary(
                '/Delete/DeleteItemRequest',
                request_serializer=market__pb2.DeleteItem.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class DeleteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteItemRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteItemRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItemRequest,
                    request_deserializer=market__pb2.DeleteItem.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Delete', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Delete(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteItemRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Delete/DeleteItemRequest',
            market__pb2.DeleteItem.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DisplayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DisplaySellerItems = channel.unary_unary(
                '/Display/DisplaySellerItems',
                request_serializer=market__pb2.DisplayAllRequest.SerializeToString,
                response_deserializer=market__pb2.ItemList.FromString,
                )


class DisplayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisplayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DisplaySellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=market__pb2.DisplayAllRequest.FromString,
                    response_serializer=market__pb2.ItemList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Display', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Display(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Display/DisplaySellerItems',
            market__pb2.DisplayAllRequest.SerializeToString,
            market__pb2.ItemList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchItem = channel.unary_unary(
                '/Search/SearchItem',
                request_serializer=market__pb2.SearchRequest.SerializeToString,
                response_deserializer=market__pb2.ItemList.FromString,
                )


class SearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=market__pb2.SearchRequest.FromString,
                    response_serializer=market__pb2.ItemList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Search(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Search/SearchItem',
            market__pb2.SearchRequest.SerializeToString,
            market__pb2.ItemList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BuyItemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuyItemRequest = channel.unary_unary(
                '/BuyItem/BuyItemRequest',
                request_serializer=market__pb2.Buy.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class BuyItemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuyItemRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyItemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuyItemRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItemRequest,
                    request_deserializer=market__pb2.Buy.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuyItem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyItem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuyItemRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyItem/BuyItemRequest',
            market__pb2.Buy.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AddToWishListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToWishListRequest = channel.unary_unary(
                '/AddToWishList/AddToWishListRequest',
                request_serializer=market__pb2.Wish.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class AddToWishListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToWishListRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddToWishListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToWishListRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishListRequest,
                    request_deserializer=market__pb2.Wish.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AddToWishList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddToWishList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToWishListRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AddToWishList/AddToWishListRequest',
            market__pb2.Wish.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RateItemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RateItemRequest = channel.unary_unary(
                '/RateItem/RateItemRequest',
                request_serializer=market__pb2.Rate.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class RateItemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RateItemRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateItemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RateItemRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItemRequest,
                    request_deserializer=market__pb2.Rate.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RateItem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RateItem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RateItemRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RateItem/RateItemRequest',
            market__pb2.Rate.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NotifyStub(object):
    """-------------------------------------------------------------------------
    10. Notify client. The market sends this.
    -------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyUpdate = channel.unary_unary(
                '/Notify/NotifyUpdate',
                request_serializer=market__pb2.Item2.SerializeToString,
                response_deserializer=market__pb2.Reply.FromString,
                )


class NotifyServicer(object):
    """-------------------------------------------------------------------------
    10. Notify client. The market sends this.
    -------------------------------------------------------------------------

    """

    def NotifyUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyUpdate,
                    request_deserializer=market__pb2.Item2.FromString,
                    response_serializer=market__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Notify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notify(object):
    """-------------------------------------------------------------------------
    10. Notify client. The market sends this.
    -------------------------------------------------------------------------

    """

    @staticmethod
    def NotifyUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Notify/NotifyUpdate',
            market__pb2.Item2.SerializeToString,
            market__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
